CREATE TABLE products (
  id_product        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_product      VARCHAR(300) NOT NULL,
  slug_product      VARCHAR(200) NOT NULL UNIQUE,
  descricao_product TEXT NOT NULL,
  imagemurl_product VARCHAR(600) NOT NULL,
  categoria_product VARCHAR(100) NOT NULL,
  ativo             BOOLEAN DEFAULT TRUE,
  created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE prices (
  id_price          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id        INTEGER NOT NULL REFERENCES products(id_product) ON DELETE CASCADE,
  stripe_price_id   VARCHAR(50) NOT NULL UNIQUE,
  amount_price      INTEGER NOT NULL,
  currency_price    VARCHAR(10) NOT NULL DEFAULT 'BRL',
  vigente_price     BOOLEAN DEFAULT TRUE
);

CREATE TABLE inventory (
  id_inventory      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id        INTEGER NOT NULL REFERENCES products(id_product) ON DELETE CASCADE,
  qty_on_hand       INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE orders (
  id_order              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               INTEGER NOT NULL REFERENCES users(id_user) ON DELETE CASCADE,
  status_order          TEXT DEFAULT 'pending' CHECK (status_order IN ('pending','paid','canceled','fulfilled','picked_up')),
  total_orders          INTEGER NOT NULL,
  currency_order        VARCHAR(10) NOT NULL DEFAULT 'BRL',
  stripe_checkout_id    VARCHAR(100) NOT NULL UNIQUE,
  stripe_payment_intent VARCHAR(100) NOT NULL UNIQUE,
  pickup_qr_token       VARCHAR(300),
  created_at            TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
  id_items         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id         INTEGER NOT NULL REFERENCES orders(id_order) ON DELETE CASCADE,
  product_id       INTEGER NOT NULL REFERENCES products(id_product),
  qty_items        INTEGER NOT NULL CHECK (qty_items > 0),
  unit_amount      INTEGER NOT NULL,
  subtotal_amount  INTEGER NOT NULL
);

CREATE TABLE audit_logs (
  id_logs        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id  INTEGER NOT NULL REFERENCES users(id_user),
  action_logs    VARCHAR(50) NOT NULL,
  entity_logs    VARCHAR(50) NOT NULL,
  entity_id      INTEGER NOT NULL,
  payload_json   JSONB,
  created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE webhook_events (
  id_webhook_events  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_event_id    VARCHAR(50) NOT NULL UNIQUE,
  type_webhook       VARCHAR(100) NOT NULL,
  raw_json           JSONB NOT NULL,
  processed          BOOLEAN DEFAULT FALSE,
  created_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

